# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Carl H. Lubba
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- DN_HistogramMode_5(x)
#'
DN_HistogramMode_5 <- function(x) {
    .Call('_catchEmAll_DN_HistogramMode_5', PACKAGE = 'catchEmAll', x)
}

#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Carl H. Lubba
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- DN_HistogramMode_10(x)
#'
DN_HistogramMode_10 <- function(x) {
    .Call('_catchEmAll_DN_HistogramMode_10', PACKAGE = 'catchEmAll', x)
}

#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Carl H. Lubba
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- CO_f1ecac(x)
#'
CO_f1ecac <- function(x) {
    .Call('_catchEmAll_CO_f1ecac', PACKAGE = 'catchEmAll', x)
}

#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Carl H. Lubba
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- CO_FirstMin_ac(x)
#'
CO_FirstMin_ac <- function(x) {
    .Call('_catchEmAll_CO_FirstMin_ac', PACKAGE = 'catchEmAll', x)
}

#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Carl H. Lubba
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- CO_HistogramAMI_even_2_5(x)
#'
CO_HistogramAMI_even_2_5 <- function(x) {
    .Call('_catchEmAll_CO_HistogramAMI_even_2_5', PACKAGE = 'catchEmAll', x)
}

#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Carl H. Lubba
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- CO_trev_1_num(x)
#'
CO_trev_1_num <- function(x) {
    .Call('_catchEmAll_CO_trev_1_num', PACKAGE = 'catchEmAll', x)
}

#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Carl H. Lubba
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- MD_hrv_classic_pnn40(x)
#'
MD_hrv_classic_pnn40 <- function(x) {
    .Call('_catchEmAll_MD_hrv_classic_pnn40', PACKAGE = 'catchEmAll', x)
}

#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Carl H. Lubba
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- SB_BinaryStats_mean_longstretch1(x)
#'
SB_BinaryStats_mean_longstretch1 <- function(x) {
    .Call('_catchEmAll_SB_BinaryStats_mean_longstretch1', PACKAGE = 'catchEmAll', x)
}

#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Carl H. Lubba
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- SB_TransitionMatrix_3ac_sumdiagcov(x)
#'
SB_TransitionMatrix_3ac_sumdiagcov <- function(x) {
    .Call('_catchEmAll_SB_TransitionMatrix_3ac_sumdiagcov', PACKAGE = 'catchEmAll', x)
}

#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Carl H. Lubba
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- PD_PeriodicityWang_th0_01(x)
#'
PD_PeriodicityWang_th0_01 <- function(x) {
    .Call('_catchEmAll_PD_PeriodicityWang_th0_01', PACKAGE = 'catchEmAll', x)
}

#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Carl H. Lubba
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- CO_Embed2_Dist_tau_d_expfit_meandiff(x)
#'
CO_Embed2_Dist_tau_d_expfit_meandiff <- function(x) {
    .Call('_catchEmAll_CO_Embed2_Dist_tau_d_expfit_meandiff', PACKAGE = 'catchEmAll', x)
}

#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Carl H. Lubba
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- IN_AutoMutualInfoStats_40_gaussian_fmmi(x)
#'
IN_AutoMutualInfoStats_40_gaussian_fmmi <- function(x) {
    .Call('_catchEmAll_IN_AutoMutualInfoStats_40_gaussian_fmmi', PACKAGE = 'catchEmAll', x)
}

#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Carl H. Lubba
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- FC_LocalSimple_mean1_tauresrat(x)
#'
FC_LocalSimple_mean1_tauresrat <- function(x) {
    .Call('_catchEmAll_FC_LocalSimple_mean1_tauresrat', PACKAGE = 'catchEmAll', x)
}

#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Carl H. Lubba
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- DN_OutlierInclude_p_001_mdrmd(x)
#'
DN_OutlierInclude_p_001_mdrmd <- function(x) {
    .Call('_catchEmAll_DN_OutlierInclude_p_001_mdrmd', PACKAGE = 'catchEmAll', x)
}

#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Carl H. Lubba
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- DN_OutlierInclude_n_001_mdrmd(x)
#'
DN_OutlierInclude_n_001_mdrmd <- function(x) {
    .Call('_catchEmAll_DN_OutlierInclude_n_001_mdrmd', PACKAGE = 'catchEmAll', x)
}

#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Carl H. Lubba
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- SP_Summaries_welch_rect_area_5_1(x)
#'
SP_Summaries_welch_rect_area_5_1 <- function(x) {
    .Call('_catchEmAll_SP_Summaries_welch_rect_area_5_1', PACKAGE = 'catchEmAll', x)
}

#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Carl H. Lubba
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- SB_BinaryStats_diff_longstretch0(x)
#'
SB_BinaryStats_diff_longstretch0 <- function(x) {
    .Call('_catchEmAll_SB_BinaryStats_diff_longstretch0', PACKAGE = 'catchEmAll', x)
}

#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Carl H. Lubba
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- SB_MotifThree_quantile_hh(x)
#'
SB_MotifThree_quantile_hh <- function(x) {
    .Call('_catchEmAll_SB_MotifThree_quantile_hh', PACKAGE = 'catchEmAll', x)
}

#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Carl H. Lubba
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- SC_FluctAnal_2_rsrangefit_50_1_logi_prop_r1(x)
#'
SC_FluctAnal_2_rsrangefit_50_1_logi_prop_r1 <- function(x) {
    .Call('_catchEmAll_SC_FluctAnal_2_rsrangefit_50_1_logi_prop_r1', PACKAGE = 'catchEmAll', x)
}

#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Carl H. Lubba
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- SC_FluctAnal_2_dfa_50_1_2_logi_prop_r1(x)
#'
SC_FluctAnal_2_dfa_50_1_2_logi_prop_r1 <- function(x) {
    .Call('_catchEmAll_SC_FluctAnal_2_dfa_50_1_2_logi_prop_r1', PACKAGE = 'catchEmAll', x)
}

#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Carl H. Lubba
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- SP_Summaries_welch_rect_centroid(x)
#'
SP_Summaries_welch_rect_centroid <- function(x) {
    .Call('_catchEmAll_SP_Summaries_welch_rect_centroid', PACKAGE = 'catchEmAll', x)
}

#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Carl H. Lubba
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- FC_LocalSimple_mean3_stderr(x)
#'
FC_LocalSimple_mean3_stderr <- function(x) {
    .Call('_catchEmAll_FC_LocalSimple_mean3_stderr', PACKAGE = 'catchEmAll', x)
}

#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Trent Henderson
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- SY_DriftingMean50_min(x)
#'
SY_DriftingMean50_min <- function(x) {
    .Call('_catchEmAll_SY_DriftingMean50_min', PACKAGE = 'catchEmAll', x)
}

#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Trent Henderson
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- CO_AddNoise_1_even_10_ami_at_10(x)
#'
CO_AddNoise_1_even_10_ami_at_10 <- function(x) {
    .Call('_catchEmAll_CO_AddNoise_1_even_10_ami_at_10', PACKAGE = 'catchEmAll', x)
}

#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Trent Henderson
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- AC_nl_036(x)
#'
AC_nl_036 <- function(x) {
    .Call('_catchEmAll_AC_nl_036', PACKAGE = 'catchEmAll', x)
}

#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Trent Henderson
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- AC_nl_035(x)
#'
AC_nl_035 <- function(x) {
    .Call('_catchEmAll_AC_nl_035', PACKAGE = 'catchEmAll', x)
}

#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Trent Henderson
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- AC_nl_112(x)
#'
AC_nl_112 <- function(x) {
    .Call('_catchEmAll_AC_nl_112', PACKAGE = 'catchEmAll', x)
}

#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Trent Henderson
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- IN_AutoMutualInfoStats_diff_20_gaussian_ami8(x)
#'
IN_AutoMutualInfoStats_diff_20_gaussian_ami8 <- function(x) {
    .Call('_catchEmAll_IN_AutoMutualInfoStats_diff_20_gaussian_ami8', PACKAGE = 'catchEmAll', x)
}

#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Trent Henderson
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- CO_HistogramAMI_even_10_3(x)
#'
CO_HistogramAMI_even_10_3 <- function(x) {
    .Call('_catchEmAll_CO_HistogramAMI_even_10_3', PACKAGE = 'catchEmAll', x)
}

#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Trent Henderson
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- CO_HistogramAMI_even_2_3(x)
#'
CO_HistogramAMI_even_2_3 <- function(x) {
    .Call('_catchEmAll_CO_HistogramAMI_even_2_3', PACKAGE = 'catchEmAll', x)
}

#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Trent Henderson
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- CO_TranslateShape_circle_35_pts_statav4_m(x)
#'
CO_TranslateShape_circle_35_pts_statav4_m <- function(x) {
    .Call('_catchEmAll_CO_TranslateShape_circle_35_pts_statav4_m', PACKAGE = 'catchEmAll', x)
}

#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Trent Henderson
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- CO_TranslateShape_circle_35_pts_std(x)
#'
CO_TranslateShape_circle_35_pts_std <- function(x) {
    .Call('_catchEmAll_CO_TranslateShape_circle_35_pts_std', PACKAGE = 'catchEmAll', x)
}

#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Trent Henderson
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- DN_RemovePoints_absclose_05_ac2rat(x)
#'
DN_RemovePoints_absclose_05_ac2rat <- function(x) {
    .Call('_catchEmAll_DN_RemovePoints_absclose_05_ac2rat', PACKAGE = 'catchEmAll', x)
}

#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Trent Henderson
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- FC_LoopLocalSimple_mean_stderr_chn(x)
#'
FC_LoopLocalSimple_mean_stderr_chn <- function(x) {
    .Call('_catchEmAll_FC_LoopLocalSimple_mean_stderr_chn', PACKAGE = 'catchEmAll', x)
}

#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Trent Henderson
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- PH_Walker_momentum_5_w_momentumzcross(x)
#'
PH_Walker_momentum_5_w_momentumzcross <- function(x) {
    .Call('_catchEmAll_PH_Walker_momentum_5_w_momentumzcross', PACKAGE = 'catchEmAll', x)
}

#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Trent Henderson
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- PH_Walker_biasprop_05_01_sw_meanabsdiff(x)
#'
PH_Walker_biasprop_05_01_sw_meanabsdiff <- function(x) {
    .Call('_catchEmAll_PH_Walker_biasprop_05_01_sw_meanabsdiff', PACKAGE = 'catchEmAll', x)
}

#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Trent Henderson
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- ST_LocalExtrema_n100_diffmaxabsmin(x)
#'
ST_LocalExtrema_n100_diffmaxabsmin <- function(x) {
    .Call('_catchEmAll_ST_LocalExtrema_n100_diffmaxabsmin', PACKAGE = 'catchEmAll', x)
}

#' @param x a numerical time-series input vector
#' @return scalar value that denotes the calculated time-series statistic
#' @author Trent Henderson
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- SC_FluctAnal_2_dfa_50_2_logi_r2_se2(x)
#'
SC_FluctAnal_2_dfa_50_2_logi_r2_se2 <- function(x) {
    .Call('_catchEmAll_SC_FluctAnal_2_dfa_50_2_logi_r2_se2', PACKAGE = 'catchEmAll', x)
}

#'
#' @param x a numeric vector, preferably of feature values computed by other package functions
#' @return x a numeric vector, rescaled into the [0,1] sigmoidal range
#' @author Trent Henderson, 18 March 2021
#' @export
#' @examples
#' x <- seq(from = 1, to = 1000, by = 1)
#' outs <- norm_scaler(x)
#'
norm_scaler <- function(x) {
    .Call('_catchEmAll_norm_scaler', PACKAGE = 'catchEmAll', x)
}

